---
title: "Exercise 2"
output: html_document
---


```{r}
#read data again and check str() and head()
lrn2014 <- read.csv("C:/Users/Pyrintö/Documents/GitHub/IODS-project/learning2014.csv")
str(lrn2014)
#deep, stra and surf are numeric but since nothing was mentioned about this they weren't changed to integers
head(lrn2014)

library(ggplot2)
library(dplyr)


```

We check how the different variables correlate to the points.
```{r}

summary(lrn2014)


# initialize plot with data and aesthetic mapping
p1 <- ggplot(lrn2014, aes(x = Attitude, y = Points))


# define the visualization type (points)
p2 <- p1 + geom_point()


# add a regression line
p3 <- p2 + geom_smooth(method = "lm")

# add a main title and draw the plot
p4 <- p3 + ggtitle("Student's attitude versus exam points")
p4



```


```{r}

# initialize plot with data and aesthetic mapping
p1 <- ggplot(lrn2014, aes(x = Age, y = Points))


# define the visualization type (points)
p2 <- p1 + geom_point()


# add a regression line
p3 <- p2 + geom_smooth(method = "lm")

# add a main title and draw the plot
p4 <- p3 + ggtitle("Student's age versus exam points")
p4



```


```{r}

# initialize plot with data and aesthetic mapping
p1 <- ggplot(lrn2014, aes(x =deep, y = Points))


# define the visualization type (points)
p2 <- p1 + geom_point()


# add a regression line
p3 <- p2 + geom_smooth(method = "lm")

# add a main title and draw the plot
p4 <- p3 + ggtitle("Student's deep questions versus exam points")
p4



```



```{r}

# initialize plot with data and aesthetic mapping
p1 <- ggplot(lrn2014, aes(x =stra, y = Points))


# define the visualization type (points)
p2 <- p1 + geom_point()


# add a regression line
p3 <- p2 + geom_smooth(method = "lm")

# add a main title and draw the plot
p4 <- p3 + ggtitle("Student's strategic questions versus exam points")
p4



```



```{r}

# initialize plot with data and aesthetic mapping
p1 <- ggplot(lrn2014, aes(x =surf, y = Points))


# define the visualization type (points)
p2 <- p1 + geom_point()


# add a regression line
p3 <- p2 + geom_smooth(method = "lm")

# add a main title and draw the plot
p4 <- p3 + ggtitle("Student's surf questions versus exam points")
p4



```
We check it there is a statistically significant relation with the points.
```{r}

model<-lm(Points~Age+Attitude+stra,data=lrn2014)

summary(model)



```


Since only the attitude is statistically significant to the points the age and strategic questions were removed.

```{r}

model<-lm(Points~Attitude,data=lrn2014)

summary(model)

plot(model)

```

